package com.sep.psp.back.feature_payment.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;

import java.math.BigDecimal;
import java.time.LocalDateTime;

@Schema(description = "Request sent by a web shop to create a PSP payment transaction.")
public record CreatePaymentRequest(

        @Schema(
                description = "Merchant identifier issued by PSP.",
                example = "MER-TEST0001"
        )
        @NotBlank
        String merchantId,

        @Schema(
                description = "Plain merchant password/API key used to authenticate the web shop request. PSP stores only the hashed value.",
                example = "mrc_test_api_key_for_local_dev_12345",
                format = "password"
        )
        @NotBlank
        String merchantPassword,

        @Schema(
                description = "Seller reference inside the merchant account.",
                example = "MAIN_SELLER"
        )
        @NotBlank
        String sellerReference,

        @Schema(
                description = "Payment amount calculated by the web shop backend.",
                example = "105.00"
        )
        @NotNull
        @DecimalMin(value = "0.01")
        BigDecimal amount,

        @Schema(
                description = "Payment currency.",
                example = "RSD"
        )
        @NotBlank
        String currency,

        @Schema(
                description = "Merchant order identifier generated by the web shop.",
                example = "RES-7f9f5d3a-3d14-4fd8-b8df-2c5dca7c77d2"
        )
        @NotBlank
        String merchantOrderId,

        @Schema(
                description = "Merchant timestamp when the payment was created.",
                example = "2026-06-08T12:00:00"
        )
        @NotNull
        LocalDateTime merchantTimestamp
) {
}