package com.sep.psp.back.feature_payment.dto;

import io.swagger.v3.oas.annotations.media.Schema;

import java.math.BigDecimal;

@Schema(description = "Request sent by PSP to payment plugin to initiate selected payment method flow.")
public record PluginPaymentInitiationRequest(

        @Schema(
                description = "PSP payment transaction identifier.",
                example = "0422dcd4-1c87-41a2-8e71-d3176d41eedd"
        )
        String paymentId,

        @Schema(
                description = "Merchant identifier issued by PSP.",
                example = "MER-TEST0001"
        )
        String merchantId,

        @Schema(
                description = "Seller reference inside the merchant account.",
                example = "MAIN_SELLER"
        )
        String sellerReference,

        @Schema(
                description = "Selected payment method code.",
                example = "MOCK_PAY"
        )
        String paymentMethodCode,

        @Schema(
                description = "Payment amount.",
                example = "105.00"
        )
        BigDecimal amount,

        @Schema(
                description = "Payment currency.",
                example = "EUR"
        )
        String currency,

        @Schema(
                description = "Merchant order identifier generated by the web shop.",
                example = "RES-7f9f5d3a-3d14-4fd8-b8df-2c5dca7c77d2"
        )
        String merchantOrderId
) {
}