#If there is no .env file in the resources directory, comment out the line below
spring.config.import=optional:classpath:.env[.properties]
spring.application.name=bank-backend

server.port=${BANK_SERVER_PORT}

spring.datasource.url=jdbc:postgresql://${BANK_DB_HOST}:${BANK_DB_PORT}/${BANK_DB_NAME}
spring.datasource.username=${BANK_DB_USERNAME}
spring.datasource.password=${BANK_DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false

server.error.include-message=always
spring.output.ansi.enabled=ALWAYS

app.bank.payment-page-base-url=${BANK_PAYMENT_PAGE_BASE_URL}

logging.level.root=ERROR
logging.level.org.springframework=ERROR
logging.level.org.hibernate=ERROR
logging.level.com.zaxxer.hikari=ERROR
logging.level.com.sep.bank.back=INFO

logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} | %clr(%-5level) | %msg%n

logging.file.name=logs/bank-backend.log