#If there is no .env file in the resources directory, comment out the line below
spring.config.import=optional:file:.env[.properties]
spring.application.name=bank-backend

server.port=${SERVER_PORT:5104}
server.ssl.enabled=${SERVER_SSL_ENABLED:true}
server.ssl.key-store=${SERVER_SSL_KEY_STORE:classpath:certs/keystore.p12}
server.ssl.key-store-password=${SERVER_SSL_KEY_STORE_PASSWORD:changeit}
server.ssl.key-store-type=${SERVER_SSL_KEY_STORE_TYPE:PKCS12}
server.ssl.key-alias=${SERVER_SSL_KEY_ALIAS:bankbackend}

#Errors
server.error.include-message=never

# Console colors
spring.output.ansi.enabled=ALWAYS

# General logging
logging.level.root=ERROR
logging.level.org.springframework=ERROR
logging.level.org.springframework.security=ERROR
logging.level.org.hibernate=ERROR
logging.level.com.zaxxer.hikari=ERROR

# Show only our structured business logs
logging.level.com.sep.bank.back=ERROR
logging.level.com.sep.bank.back.shared.logging.service.impl.AppLoggerServiceImpl=INFO

# Hibernate SQL output
spring.jpa.properties.hibernate.show_sql=false
spring.jpa.properties.hibernate.format_sql=false

# Disable open-in-view warning properly
spring.jpa.open-in-view=false

# Console log format
logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} | %clr(%-5level) | %clr(%-15X{feature:-UNSPECIFIED}){cyan} | %clr(%-30X{action:-UNSPECIFIED}){magenta} | %msg%n

# File logging
logging.file.name=logs/bank-backend.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} | %-5level | %-15X{feature:-APP} | %-30X{action:-UNSPECIFIED} | %msg%n

spring.datasource.url=jdbc:postgresql://${BANK_DB_HOST}:${BANK_DB_PORT}/${BANK_DB_NAME}
spring.datasource.username=${BANK_DB_USERNAME}
spring.datasource.password=${BANK_DB_PASSWORD}
#Update
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=false
spring.sql.init.mode=never
#Drop and fill
#spring.jpa.hibernate.ddl-auto=create
#spring.jpa.defer-datasource-initialization=true
#spring.sql.init.mode=always

# Security
app.security.expected-plugin-code=${BANK_EXPECTED_PLUGIN_CODE}
app.security.plugin-secret=${BANK_PLUGIN_SECRET}
app.security.signature-max-timestamp-age-minutes=5
app.security.card-secret=${BANK_CARD_SECRET}
app.security.pan-hash-secret=${BANK_CARD_PAN_SECRET}

# Plugin
app.plugin.callback.max-attempts=3
app.plugin.callback.retry-delay-ms=1000

# Other
app.bank.payment-page-base-url=${BANK_PAYMENT_PAGE_BASE_URL}
app.bank.payment-url-expiration-minutes=15
app.bank.expired-payment-check-delay-ms=60000
app.bank.expired-payment-check-initial-delay-ms=10000