package com.sep.bank.back.feature_payment.dto;

import io.swagger.v3.oas.annotations.media.Schema;

@Schema(description = "Response returned by bank backend after creating bank payment session.")
public record CreatePaymentResponse(

        @Schema(
                description = "Bank payment identifier generated by bank backend.",
                example = "5f2f3b2c-0c5f-4c1a-9b28-7fcb8d4a5f90"
        )
        String bankPaymentId,

        @Schema(
                description = "Bank payment page URL where customer should be redirected.",
                example = "http://localhost:8083/payments/5f2f3b2c-0c5f-4c1a-9b28-7fcb8d4a5f90"
        )
        String paymentUrl
) {
}