package com.sep.bank.back.feature_payment.dto;

import com.sep.bank.back.feature_payment.enumeration.PaymentMethod;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;

import java.math.BigDecimal;
import java.time.LocalDateTime;

@Schema(description = "Request sent by psp to bank backend to create bank payment session.")
public record CreatePaymentRequest(

        @Schema(
                description = "Seller's merchant identifier in the bank system.",
                example = "BANK_MERCHANT_001"
        )
        @NotBlank
        String bankMerchantId,

        @Schema(
                description = "Payment amount.",
                example = "100.00"
        )
        @NotNull
        @DecimalMin("0.01")
        BigDecimal amount,

        @Schema(
                description = "Payment currency.",
                example = "RSD"
        )
        @NotBlank
        String currency,

        @Schema(
                description = "System Trace Audit Number used for tracking payment request.",
                example = "123456"
        )
        @NotBlank
        String stan,

        @Schema(
                description = "Timestamp generated by plugin/PSP side when creating payment request toward the bank.",
                example = "2026-06-12T12:30:00"
        )
        @NotNull
        LocalDateTime pspTimestamp,

        @Schema(
                description = "Bank payment method for this payment session.",
                example = "CARD"
        )
        @NotNull
        PaymentMethod paymentMethod,

        @Schema(
                description = "Browser redirect URL after successful payment.",
                example = "https://localhost:3001/payment/success"
        )
        @NotBlank
                String successUrl,

        @Schema(
                description = "Browser redirect URL after failed payment.",
                example = "https://localhost:3001/payment/failed"
        )
        @NotBlank
        String failUrl,

        @Schema(
                description = "Browser redirect URL after technical payment error.",
                example = "https://localhost:3001/payment/error"
        )
        @NotBlank
        String errorUrl,

        @Schema(
                description = "Plugin callback URL used by the bank to notify plugin/PSP about final payment result.",
                example = "https://localhost:8086/api/plugin/payments/bank-callback"
        )
        @NotBlank
        String pluginCallbackUrl


) {
}