#If there is no .env file in the resources directory, comment out the line below
spring.config.import=optional:file:.env[.properties]
spring.application.name=back

server.port=${SERVER_PORT:5101}
server.ssl.enabled=${SERVER_SSL_ENABLED:true}
server.ssl.key-store=${SERVER_SSL_KEY_STORE:classpath:certs/keystore.p12}
server.ssl.key-store-password=${SERVER_SSL_KEY_STORE_PASSWORD:changeit}
server.ssl.key-store-type=${SERVER_SSL_KEY_STORE_TYPE:PKCS12}
server.ssl.key-alias=${SERVER_SSL_KEY_ALIAS:wsbackend}

# Errors
server.error.include-message=never

# Console colors
spring.output.ansi.enabled=ALWAYS

# General logging
logging.level.root=ERROR
logging.level.org.springframework=ERROR
logging.level.org.springframework.security=ERROR
logging.level.org.hibernate=ERROR
logging.level.com.zaxxer.hikari=ERROR

# Show only our structured business logs
logging.level.com.sep.web_shop.back=ERROR
logging.level.com.sep.web_shop.back.shared.logging.service.impl.AppLoggerServiceImpl=INFO

# Hibernate SQL output
spring.jpa.properties.hibernate.show_sql=false
spring.jpa.properties.hibernate.format_sql=false

# Disable open-in-view warning properly
spring.jpa.open-in-view=false

# Console log format
logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} | %clr(%-5level) | %clr(%-15X{feature:-UNSPECIFIED}){cyan} | %clr(%-30X{action:-UNSPECIFIED}){magenta} | %msg%n

# File logging
logging.file.name=logs/web-shop.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} | %-5level | %-15X{feature:-APP} | %-30X{action:-UNSPECIFIED} | %msg%n

#JWT
jwt.secret=${JWT_SECRET_KEY}

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.show-sql=false
spring.jpa.database=postgresql
#Update
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.defer-datasource-initialization=false
#spring.sql.init.mode=never
#Drop and fill
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# PSP Info
app.psp.base-url=${PSP_BASE_URL}
app.psp.merchant-id=${PSP_MERCHANT_ID}
app.psp.merchant-password=${PSP_MERCHANT_PASSWORD}
app.psp.seller-reference=${PSP_SELLER_REFERENCE}
app.psp.currency=${PSP_CURRENCY}

# RabbitMQ
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}
app.rabbitmq.payment-notifications.exchange=${RABBITMQ_PAYMENT_NOTIFICATIONS_EXCHANGE}
app.rabbitmq.payment-notifications.queue=${RABBITMQ_PAYMENT_NOTIFICATIONS_QUEUE}
app.rabbitmq.payment-notifications.routing-key=${RABBITMQ_PAYMENT_NOTIFICATIONS_ROUTING_KEY}

# Other
app.images.folder=${IMAGES_FOLDER_PATH}