server {
    listen 443 ssl;

    server_name localhost;

    ssl_certificate /etc/nginx/certs/nginx.crt;
    ssl_certificate_key /etc/nginx/certs/nginx.key;

    location /images/ {
        alias /usr/share/nginx/html/images/;
        autoindex off;
    }
}