version: '3.8'

name: sep

services:
  ws-postgres:
    image: postgres:17
    container_name: ws-postgres
    environment:
      - POSTGRES_USER=${WS_DB_USERNAME}
      - POSTGRES_PASSWORD=${WS_DB_PASSWORD}
      - POSTGRES_DB=${WS_DB_NAME}
    volumes:
      - ws-postgres-data:/var/lib/postgresql/data
    ports:
      - ${WS_DB_PORT}:5432
    networks:
      - app-network

  psp-postgres:
    image: postgres:17
    container_name: psp-postgres
    environment:
      - POSTGRES_USER=${PSP_DB_USERNAME}
      - POSTGRES_PASSWORD=${PSP_DB_PASSWORD}
      - POSTGRES_DB=${PSP_DB_NAME}
    volumes:
      - psp-postgres-data:/var/lib/postgresql/data
    ports:
      - ${PSP_DB_PORT}:5432
    networks:
      - app-network

  bank-postgres:
    image: postgres:17
    container_name: bank-postgres
    environment:
      - POSTGRES_USER=${BANK_DB_USERNAME}
      - POSTGRES_PASSWORD=${BANK_DB_PASSWORD}
      - POSTGRES_DB=${BANK_DB_NAME}
    volumes:
      - bank-postgres-data:/var/lib/postgresql/data
    ports:
      - ${BANK_DB_PORT}:5432
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - ${PGADMIN_PORT}:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - ws-postgres
      - psp-postgres
    networks:
      - app-network
    restart: always

  nginx:
    image: nginx:alpine
    container_name: ws-nginx
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./vehicles:/usr/share/nginx/html/images/vehicles:ro
    networks:
      - app-network
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: sep-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    ports:
      - ${RABBITMQ_PORT}:5672
      - ${RABBITMQ_MANAGEMENT_PORT}:15672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - app-network
    restart: unless-stopped

volumes:
  ws-postgres-data:
  psp-postgres-data:
  pgadmin-data:
  rabbitmq-data:
  bank-postgres-data:

networks:
  app-network:
    driver: bridge