#If there is no .env file in the resources directory, comment out the line below
spring.config.import=optional:classpath:.env[.properties]
spring.application.name=back
server.port=${SERVER_PORT}

# Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.enable-hateoas=false
springdoc.enable-data-rest=false

#Errors
server.error.include-message=always

# Console colors
spring.output.ansi.enabled=ALWAYS

# General logging
logging.level.root=ERROR
logging.level.org.springframework=ERROR
logging.level.org.springframework.security=ERROR
logging.level.org.hibernate=ERROR
logging.level.com.zaxxer.hikari=ERROR

# Show only our structured business logs
logging.level.com.sep.psp.back=ERROR
logging.level.com.sep.psp.back.shared.logging.service.impl.AppLoggerServiceImpl=INFO

# Hibernate SQL output
spring.jpa.properties.hibernate.show_sql=false
spring.jpa.properties.hibernate.format_sql=false

# Disable open-in-view warning properly
spring.jpa.open-in-view=false

# Console log format
logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} | %clr(%-5level) | %clr(%-15X{feature:-UNSPECIFIED}){cyan} | %clr(%-30X{action:-UNSPECIFIED}){magenta} | %msg%n

# File logging
logging.file.name=logs/psp-core.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} | %-5level | %-15X{feature:-APP} | %-30X{action:-UNSPECIFIED} | %msg%n

#JWT
jwt.secret=${JWT_SECRET_KEY}

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.show-sql=false
spring.jpa.database=postgresql
#Update
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.defer-datasource-initialization=false
#spring.sql.init.mode=never
#Drop and fill
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# Generator
app.merchant-id.prefix=${MERCHANT_ID_PREFIX}
app.merchant-id.alphabet=${MERCHANT_ID_ALPHABET}
app.merchant-id.length=${MERCHANT_ID_LENGTH}
app.merchant-password.prefix=${MERCHANT_PASSWORD_PREFIX}
app.merchant-password.alphabet=${MERCHANT_PASSWORD_ALPHABET}
app.merchant-password.length=${MERCHANT_PASSWORD_LENGTH}

# Plugin Encryption
app.plugin.encryption-key=${PLUGIN_SECRET_ENCRYPTION_KEY_BASE64}
app.plugin.encryption-max-timestamp-age-minutes=5