package com.sep.bank.plugin.back.feature_payment.dto.bank;

import com.sep.bank.plugin.back.feature_payment.enumeration.PluginPaymentStatus;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;

import java.time.LocalDateTime;

@Schema(description = "Request sent by bank backend to bank-payment-plugin after payment processing is completed.")
public record BankPaymentCallbackRequest(

        @Schema(
                description = "Payment identifier generated by bank backend.",
                example = "4ce13756-a7f4-4426-bb18-d686f509a58a"
        )
        @NotBlank
        String bankPaymentId,

        @Schema(
                description = "System Trace Audit Number used for payment tracking.",
                example = "123456"
        )
        @NotBlank
        String stan,

        @Schema(
                description = "Final payment status reported by bank backend.",
                example = "SUCCESS"
        )
        @NotNull
        PluginPaymentStatus status,

        @Schema(
                description = "Global transaction identifier generated by bank backend.",
                example = "e2bbce51-6bfb-4e69-a618-0454a8a97a59",
                nullable = true
        )
        String globalTransactionId,

        @Schema(
                description = "Timestamp generated by acquirer bank when payment processing is completed.",
                example = "2026-06-13T12:30:00",
                nullable = true
        )
        LocalDateTime acquirerTimestamp,

        @Schema(
                description = "Optional payment result message.",
                example = "Payment completed successfully.",
                nullable = true
        )
        String message
) {
}