package com.sep.bank.plugin.back.feature_payment.dto.bank;

import com.sep.bank.plugin.back.feature_payment.enumeration.PaymentResultDeliveryStatus;
import com.sep.bank.plugin.back.feature_payment.enumeration.PluginPaymentStatus;
import io.swagger.v3.oas.annotations.media.Schema;

@Schema(description = "Response returned by bank-payment-plugin after bank callback is processed.")
public record BankPaymentCallbackResponse(

        @Schema(
                description = "Payment identifier generated by bank backend.",
                example = "4ce13756-a7f4-4426-bb18-d686f509a58a"
        )
        String bankPaymentId,

        @Schema(
                description = "Stored payment status in bank-payment-plugin.",
                example = "SUCCESS"
        )
        PluginPaymentStatus status,

        @Schema(
                description = "Current delivery status of payment result inside plugin flow. For debug.",
                example = "DELIVERED_TO_PSP"
        )
        PaymentResultDeliveryStatus resultDeliveryStatus
) {
}