export const AUTH_LABELS = {
    loginTitle: "Merchant login",
    loginSubtitle: "Sign in to manage your PSP configuration.",
    registerTitle: "Register shop",
    registerSubtitle: "Create a merchant account and receive your API key.",
    username: "Username",
    password: "Password",
    adminName: "Admin name",
    merchantName: "Shop name",
    currency: "Currency",
    successUrl: "Success URL",
    failUrl: "Fail URL",
    errorUrl: "Error URL",
    loginButton: "Login",
    registerButton: "Register shop",
    signingIn: "Signing in...",
    registering: "Registering...",
    invalidCredentials: "Invalid username or password.",
    registrationFailed: "Shop registration failed.",
    noAccount: "Need to register a shop?",
    haveAccount: "Already have a merchant account?",
    apiKeyCreatedTitle: "Shop registered successfully",
    apiKeyCreatedDescription: "Save this merchant password now. It will not be shown again.",
    merchantId: "Merchant ID",
    merchantPassword: "Merchant password / API key",
    goToLogin: "Go to login",
    copy: "Copy",
    copied: "Copied to clipboard.",
};

export const NAVBAR_LABELS = {
    title: "PSP Console",
    subtitle: "Merchant administration",
    logout: "Logout",
};

export const MERCHANT_LABELS = {
    setupRequired: "Setup required",
    active: "Active",
    inactive: "Inactive",
    loadingError: "Failed to load merchant data.",
    save: "Save",
    saving: "Saving...",
    cancel: "Cancel",
    close: "Close",
    edit: "Edit",
    configure: "Configure",
    addSeller: "Add seller",

    profileTitle: "Shop profile",
    profileDescription: "Basic shop settings used during payment processing.",

    apiKeyTitle: "API credentials",
    apiKeyDescription: "Merchant password is hidden and can only be regenerated.",
    regenerateApiKey: "Regenerate API key",
    regenerateWarning: "The old merchant password will stop working. The new value will be shown only once.",
    newApiKeyTitle: "New merchant password",

    merchantId: "Merchant ID",
    merchantName: "Shop name",
    currency: "Currency",
    successUrl: "Success URL",
    failUrl: "Fail URL",
    errorUrl: "Error URL",
    adminUsername: "Admin username",
    adminName: "Admin name",
    status: "Status",

    sellersTitle: "Seller accounts",
    sellersDescription: "Configure sellers and payment methods available for each seller.",
    sellerReference: "Seller reference",
    displayName: "Display name",
    paymentMethods: "Payment methods",
    actions: "Actions",
    noPaymentMethodsConfigured: "No payment methods configured",

    createSellerTitle: "Add seller",
    editSellerTitle: "Edit seller",
    editProfileTitle: "Edit shop profile",

    sellerCreated: "Seller account created.",
    sellerUpdated: "Seller account updated.",
    profileUpdated: "Merchant profile updated.",
    apiKeyRegenerated: "Merchant password regenerated.",
    savedSuccessfully: "Changes saved successfully.",
    saveFailed: "Action failed. Please check the entered data.",

    configurePaymentMethodsTitle: "Payment method configuration",
    configurePaymentMethod: "Configure",
    reconfigurePaymentMethod: "Reconfigure",
    removePaymentMethod: "Remove",

    paymentMethodConfigurationTitle: "Payment method configuration",
    reconfigurationRequired: "Reconfiguration required",
    noConfigurationFields: "No configuration fields available for this payment method.",
    missingConfigurationValues: "Please fill in all configuration values.",
    back: "Back",
    selectedForSeller: "Selected for this seller",
};

export const SUPER_ADMIN_LABELS = {
    pluginsTitle: "Payment plugins",
    createPlugin: "Create plugin",
    pluginCode: "Plugin code",
    displayName: "Display name",
    baseUrl: "Base URL",
    adminStatus: "Admin status",
    operationalStatus: "Operational status",
    actions: "Actions",

    enabledByAdmin: "Enabled by admin",
    disabledByAdmin: "Disabled by admin",
    active: "Active",
    inactive: "Inactive",
    noBaseUrl: "Not synchronized",
    noPlugins: "No plugins found.",

    createPluginTitle: "Create expected plugin",
    createPluginDescription: "After creation, plugin secret will be shown only once.",

    pluginSecretTitle: "Plugin secret generated",
    pluginSecretDescription: "Save this value now. It will not be shown again.",
    pluginSecret: "Plugin secret",

    copy: "Copy",
    copied: "Copied to clipboard.",
    create: "Create",
    creating: "Creating...",
    cancel: "Cancel",
    close: "Close",
    enable: "Enable",
    disable: "Disable",

    loadingError: "Failed to load plugins.",
    pluginCreated: "Expected plugin created.",
    pluginStatusUpdated: "Plugin status updated.",
    saveFailed: "Action failed. Please check the entered data.",
};

export const PAYMENT_LABELS = {
    title: "Payment",
    subtitle: "Choose a payment method to continue.",
    merchant: "Merchant",
    seller: "Seller",
    amount: "Amount",
    status: "Status",
    noPaymentMethods: "No payment methods are currently available for this seller.",
    loadingError: "Failed to load payment.",
    notFound: "Payment not found.",
    continue: "Continue",
    methodSelected: "Payment method selected.",
    processing: "Processing...",
};