export const AUTH_LABELS = {
    loginTitle: "Merchant login",
    loginSubtitle: "Sign in to manage your PSP configuration.",
    registerTitle: "Register shop",
    registerSubtitle: "Create a merchant account and receive your API key.",
    username: "Username",
    password: "Password",
    adminName: "Admin name",
    merchantName: "Shop name",
    currency: "Currency",
    successUrl: "Success URL",
    failUrl: "Fail URL",
    errorUrl: "Error URL",
    loginButton: "Login",
    registerButton: "Register shop",
    signingIn: "Signing in...",
    registering: "Registering...",
    invalidCredentials: "Invalid username or password.",
    registrationFailed: "Shop registration failed.",
    noAccount: "Need to register a shop?",
    haveAccount: "Already have a merchant account?",
    apiKeyCreatedTitle: "Shop registered successfully",
    apiKeyCreatedDescription: "Save this merchant password now. It will not be shown again.",
    merchantId: "Merchant ID",
    merchantPassword: "Merchant password / API key",
    goToLogin: "Go to login",
    copy: "Copy",
    copied: "Copied to clipboard.",
};

export const NAVBAR_LABELS = {
    title: "PSP Console",
    subtitle: "Merchant administration",
    logout: "Logout",
};

export const MERCHANT_LABELS = {
    title: "Merchant administration",
    subtitle: "Manage shop profile, API credentials, sellers and payment methods.",
    setupRequired: "Setup required",
    active: "Active",
    inactive: "Inactive",
    loadingError: "Failed to load merchant data.",
    save: "Save",
    saving: "Saving...",
    cancel: "Cancel",
    close: "Close",
    edit: "Edit",
    configure: "Configure",
    addSeller: "Add seller",
    profileTitle: "Shop profile",
    profileDescription: "Basic shop settings used during payment processing.",
    apiKeyTitle: "API credentials",
    apiKeyDescription: "Merchant password is hidden and can only be regenerated.",
    regenerateApiKey: "Regenerate API key",
    regenerateWarning: "The old merchant password will stop working. The new value will be shown only once.",
    newApiKeyTitle: "New merchant password",
    merchantId: "Merchant ID",
    merchantName: "Shop name",
    currency: "Currency",
    successUrl: "Success URL",
    failUrl: "Fail URL",
    errorUrl: "Error URL",
    adminUsername: "Admin username",
    adminName: "Admin name",
    status: "Status",
    sellersTitle: "Seller accounts",
    sellersDescription: "Configure sellers and payment methods available for each seller.",
    sellerReference: "Seller reference",
    displayName: "Display name",
    paymentMethods: "Payment methods",
    actions: "Actions",
    noPaymentMethods: "No payment methods configured",
    noSellers: "No sellers found.",
    createSellerTitle: "Add seller",
    editSellerTitle: "Edit seller",
    editProfileTitle: "Edit shop profile",
    configurePaymentMethodsTitle: "Configure payment methods",
    configurePaymentMethodsDescription: "Select at least one payment method for this seller.",
    sellerCreated: "Seller account created.",
    sellerUpdated: "Seller account updated.",
    paymentMethodsUpdated: "Payment methods updated.",
    profileUpdated: "Merchant profile updated.",
    apiKeyRegenerated: "Merchant password regenerated.",
    genericError: "Something went wrong. Please try again.",
};
