package com.sep.bank.plugin.back.feature_payment.dto.psp;

import com.sep.bank.plugin.back.feature_payment.enumeration.PluginPaymentStatus;
import io.swagger.v3.oas.annotations.media.Schema;

import java.time.LocalDateTime;

@Schema(description = "Response returned by bank-payment-plugin after payment status check.")
public record PspPaymentStatusCheckResponse(

        @Schema(
                description = "Payment identifier generated by PSP.",
                example = "934a7e66-2560-4a4a-958a-6c8e9f2cfa42"
        )
        String paymentId,

        @Schema(
                description = "Current payment status known by plugin.",
                example = "SUCCESS"
        )
        PluginPaymentStatus status,

        @Schema(
                description = "Optional status message.",
                example = "Payment completed successfully.",
                nullable = true
        )
        String message,

        @Schema(
                description = "Global transaction identifier generated by bank backend.",
                example = "e2bbce51-6bfb-4e69-a618-0454a8a97a59",
                nullable = true
        )
                String globalTransactionId,

        @Schema(
                description = "Timestamp generated by acquirer bank when payment processing is completed.",
                example = "2026-06-13T12:30:00",
                nullable = true
        )
        LocalDateTime acquirerTimestamp
) {
}