package com.sep.bank.plugin.back.feature_payment.dto.psp;

import com.sep.bank.plugin.back.feature_payment.enumeration.PluginPaymentStatus;
import io.swagger.v3.oas.annotations.media.Schema;

@Schema(description = "Response returned by bank-payment-plugin after payment status check.")
public record PspPaymentStatusCheckResponse(

        @Schema(
                description = "Payment identifier generated by PSP.",
                example = "934a7e66-2560-4a4a-958a-6c8e9f2cfa42"
        )
        String paymentId,

        @Schema(
                description = "Current payment status known by plugin.",
                example = "SUCCESS"
        )
        PluginPaymentStatus status,

        @Schema(
                description = "Optional status message.",
                example = "Payment completed successfully.",
                nullable = true
        )
        String message
) {
}