package com.sep.bank.plugin.back.feature_payment.dto.psp;

import com.sep.bank.plugin.back.feature_payment.enumeration.PluginPaymentStatus;
import io.swagger.v3.oas.annotations.media.Schema;

import java.time.LocalDateTime;

@Schema(description = "Request sent by bank-payment-plugin to PSP after bank payment callback is processed.")
public record PspPaymentCallbackRequest(

        @Schema(
                description = "Final payment status reported to PSP.",
                example = "SUCCESS"
        )
        PluginPaymentStatus status,

        @Schema(
                description = "Optional payment result message.",
                example = "Payment completed successfully.",
                nullable = true
        )
        String message,

        @Schema(
                description = "System Trace Audit Number used for payment tracking.",
                example = "123456"
        )
        String stan,

        @Schema(
                description = "Global transaction identifier generated by bank backend.",
                example = "e2bbce51-6bfb-4e69-a618-0454a8a97a59",
                nullable = true
        )
        String globalTransactionId,

        @Schema(
                description = "Timestamp generated by acquirer bank when payment processing is completed.",
                example = "2026-06-13T12:30:00",
                nullable = true
        )
        LocalDateTime acquirerTimestamp
) {
}