package com.sep.bank.plugin.back.feature_payment.dto.psp;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;

@Schema(description = "Request sent by PSP to bank-payment-plugin to check payment status.")
public record PspPaymentStatusCheckRequest(

        @Schema(
                description = "Payment identifier generated by PSP.",
                example = "934a7e66-2560-4a4a-958a-6c8e9f2cfa42"
        )
        @NotBlank
        String paymentId
) {
}